//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NearestTube.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NearestTube.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Acton Town&quot;,51.503071,-0.280303
        ///&quot;Aldgate&quot;,51.514342,-0.075627
        ///&quot;Aldgate East&quot;,51.51503,-0.073162
        ///&quot;All Saints (DLR)&quot;,51.510477,-0.012625
        ///&quot;Alperton&quot;,51.541209,-0.299516
        ///&quot;Amersham&quot;,51.674129,-0.606514
        ///&quot;Angel&quot;,51.532968,-0.105581
        ///&quot;Archway&quot;,51.565491,-0.135122
        ///&quot;Arnos Grove&quot;,51.61623,-0.13427
        ///&quot;Arsenal&quot;,51.55855,-0.105456
        ///&quot;Baker Street&quot;,51.52313,-0.156904
        ///&quot;Balham&quot;,51.443183,-0.152685
        ///&quot;Bank&quot;,51.513347,-0.089
        ///&quot;Barbican&quot;,51.520215,-0.097722
        ///&quot;Barking&quot;,51.539521,0.080832
        ///&quot;Barkingside&quot;,51.586008,0.091227
        ///&quot;Barons Court&quot;, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string tube {
            get {
                return ResourceManager.GetString("tube", resourceCulture);
            }
        }
    }
}
