/*
 * Slow Regexes
 *
 * @author Rob Impey
 * @date 2010-06-23
 */


document.writeln("Slow regexes");

testString = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean non erat non tellus congue elementum. Donec consequat, odio non dictum vestibulum, nibh nibh accumsan odio, nec faucibus nibh eros ut quam. Sed et augue ligula, at tempus enim. Mauris sed lectus et eros pellentesque semper quis nec turpis. Phasellus nibh elit, varius vel viverra convallis, interdum eget nisl. Nulla lobortis turpis nec velit pharetra semper. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vestibulum fringilla ornare nisl, vel blandit justo pretium sit amet. Sed gravida sem et leo faucibus a ultrices est malesuada. Maecenas mollis tempor lectus sed luctus. Nulla sed mi eget dui pretium viverra ac a sem. Morbi congue, neque in adipiscing gravida, nibh dui feugiat metus, nec pellentesque lectus purus vitae massa. Aenean ut rhoncus dolor. Nullam id enim est, quis accumsan nulla. Donec porta laoreet consectetur. Maecenas at mi sit amet lorem tincidunt consequat sed nec tortor. Nam luctus vestibulum lorem eu cursus. Pellentesque vestibulum, quam vel sagittis iaculis, augue ante accumsan quam, nec consectetur eros augue quis quam. Fusce semper lectus ac arcu luctus iaculis. Praesent lacinia tincidunt mollis.\
\
Sed pulvinar orci id lorem dapibus nec ultricies felis posuere. Vestibulum at purus eget sem pharetra pulvinar. Nulla ac metus eget dui iaculis vulputate quis sed velit. Integer ornare sodales euismod. Duis egestas tristique massa sed ornare. Proin massa erat, malesuada et adipiscing quis, interdum sit amet magna. Proin justo purus, dapibus vitae rutrum in, adipiscing ac metus. Praesent cursus diam vel mauris fringilla quis porttitor neque sagittis. Mauris eget diam libero, sit amet dapibus erat. Aenean lacus diam, tincidunt ut accumsan vitae, rutrum a odio. Vivamus porttitor nisl quis elit vehicula nec aliquam nunc vulputate. Nam tellus ipsum, iaculis et egestas et, tristique at diam. Sed varius pellentesque eleifend. Vivamus feugiat risus enim. Pellentesque rutrum posuere nulla nec hendrerit. Donec tempor iaculis lacus ac lacinia.\
\
Vivamus ac augue libero. Integer non lectus erat. Fusce rhoncus lorem tortor, ac rhoncus odio. Duis ut ornare nulla. Ut aliquam dictum aliquam. Praesent hendrerit sapien sed sapien convallis semper varius massa consequat. In ac nisl sit amet tellus viverra ornare eu ut dolor. Pellentesque ut urna lacus, vitae condimentum nulla. Mauris auctor accumsan scelerisque. In velit massa, commodo eu suscipit id, varius in leo. Praesent ipsum orci, dignissim vel pulvinar ut, auctor eu mi. Nam et magna urna. Fusce ut tellus ac tortor accumsan ultricies eget sit amet quam. Curabitur venenatis aliquam neque vel lacinia. Sed risus ipsum, semper fringilla eleifend vel, dictum sed nibh. Quisque molestie blandit mi, eu porttitor mi euismod et. Cras aliquam leo non quam volutpat at tristique nisl elementum. Aliquam rutrum, erat vitae interdum ultrices, sem velit pretium lorem, ac lacinia velit ipsum vitae velit. Etiam bibendum fermentum neque id interdum. Nulla semper posuere metus, nec ornare felis lobortis nec.\
\
Pellentesque eget porta arcu. Mauris viverra molestie sem, et mattis magna auctor sed. Vivamus at libero vel orci elementum facilisis in sed libero. Aliquam non magna posuere nisl placerat pharetra ut a velit. In convallis, sapien et fermentum iaculis, sapien urna ultricies tellus, ac dictum quam elit at nibh. Nunc quis libero velit, id pretium urna. Pellentesque ultrices, massa non mollis suscipit, felis diam blandit dolor, eu semper ipsum sem gravida diam. Etiam a massa dolor. Proin at elit magna, pellentesque adipiscing tellus. Cras eget arcu a dui placerat vehicula sed et urna. Sed non sapien eget purus posuere luctus sit amet eu felis. Nam leo magna, dignissim at lacinia vitae, molestie a nisi.\
\
Quisque volutpat pretium lorem at viverra. Cras nec sagittis nulla. Proin aliquet enim ut ante rhoncus scelerisque. Nam porta ullamcorper molestie. Maecenas cursus aliquam vehicula. Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae dui ante. Pellentesque nec ullamcorper massa. Ut massa quam, lacinia nec ultricies eget, sagittis vitae metus. Aenean tempus malesuada facilisis. Aenean sit amet aliquet ipsum. Curabitur risus justo, venenatis vitae pretium in, tempor vel est. Nam sed mi ipsum. Duis ac metus metus, vitae rutrum nisl. Sed ut metus massa, eget bibendum tortor. Nullam pellentesque lectus non dolor rhoncus gravida. Phasellus fermentum, nisi vitae vestibulum placerat, neque turpis imperdiet magna, at tempor nisl ipsum quis nulla.\
\
Sed sit amet nisi quis tellus fringilla tincidunt at id dui. Nam nec metus nunc. Sed interdum interdum erat. Curabitur id lacus ac augue cursus pretium. Ut imperdiet auctor turpis, in volutpat nulla ornare eu. Donec ut est sapien. Donec est augue, consectetur eu laoreet ut, pharetra ut nulla. Sed sed nunc ut felis ornare volutpat. Vivamus sit amet metus mi. Maecenas quis purus velit, sit amet posuere sem. Duis felis tortor, ullamcorper sit amet scelerisque sed, dictum eu magna. Morbi vitae augue vitae nisl consequat pellentesque. Quisque vitae tristique dui. Nullam pharetra dui sed orci tempus consectetur. Pellentesque condimentum metus quis quam tempus fringilla. Duis accumsan auctor egestas. Pellentesque luctus orci vitae risus sagittis hendrerit. Ut a mattis tellus.\
\
Etiam imperdiet semper mauris vel fringilla. Nulla facilisi. Sed sed velit nulla, et convallis libero. Morbi iaculis suscipit rhoncus. Morbi sit amet ligula quam. Nunc placerat sapien eu risus ultrices ut ornare justo varius. Sed magna diam, feugiat quis laoreet et, vehicula sed leo. Donec vestibulum mollis ipsum non commodo. Maecenas id augue dolor, quis tincidunt neque. Phasellus a diam eu lorem consequat aliquet id sed augue. Maecenas nec neque eget nibh vestibulum lobortis eu quis sem.\
\
Etiam pulvinar faucibus sodales. Vivamus tempor, ligula dapibus vestibulum bibendum, sapien mi vestibulum lectus, vel accumsan massa lacus quis felis. Phasellus porta, tellus a mollis dapibus, ante dui semper augue, a condimentum mauris lorem quis velit. Phasellus dictum ullamcorper nibh ac lobortis. Sed egestas eros in est pretium auctor. Donec mollis pulvinar fringilla. Cras faucibus dictum tempor. Praesent euismod, felis et suscipit molestie, nisi ipsum feugiat lectus, nec mollis mauris leo hendrerit ante. Fusce eget tortor nulla. Nulla facilisi. Phasellus quis massa tristique libero auctor lacinia. Etiam dui quam, venenatis et sollicitudin vitae, hendrerit quis lectus. Pellentesque est massa, lobortis gravida lacinia a, tempor quis augue. Pellentesque lacinia porta mauris, sit amet feugiat lorem consequat aliquam. Sed vestibulum, tortor eu tempus vulputate, leo justo ultrices velit, eu sodales enim justo nec purus. Fusce at tristique metus.\
\
Vestibulum nec ante in diam mattis suscipit ac id libero. Ut ullamcorper, nisl vitae congue pellentesque, tellus tellus dignissim massa, at auctor augue lacus at quam. Donec nec metus diam. Cras congue, nulla vitae mattis tristique, mauris dolor lobortis nisi, et posuere purus ante sit amet ipsum. Etiam a lacus quis nisl aliquet porttitor nec a risus. Vestibulum mollis purus et mauris bibendum ut adipiscing tortor volutpat. Duis vulputate justo eu justo fermentum dictum. Nunc libero nibh, hendrerit quis dignissim eget, sagittis sit amet magna. Proin congue velit ac nisi ultrices lacinia. Donec consequat facilisis dui, at congue diam molestie et. Maecenas purus justo, congue sit amet laoreet eu, pharetra quis eros. Vivamus dolor justo, sodales ac vulputate vel, luctus et lorem. Nam interdum, turpis sollicitudin pretium rhoncus, justo sapien tempus velit, eu placerat est tortor malesuada erat. Phasellus at vulputate tellus. Morbi erat arcu, aliquam mollis aliquet aliquam, posuere nec ipsum. Sed eget dolor nulla. Nunc eget magna orci. Proin nec augue id tellus dictum sagittis sed vel elit. Aliquam aliquet, lorem at semper euismod, augue nibh ultrices magna, vel semper ante erat ac nulla. Aliquam euismod tincidunt ante eu lacinia.\
\
Suspendisse potenti. Nulla facilisi. Nunc at justo ante. Integer malesuada risus volutpat nisl adipiscing ornare. Proin a metus mauris. Pellentesque eu metus lorem. Maecenas leo urna, suscipit ut ornare in, sodales vel mauris. Aenean iaculis ante vitae odio sagittis at elementum odio venenatis. Praesent suscipit, nisl eget consectetur molestie, nulla ante pretium velit, non consectetur diam nisi vitae nisl. Praesent ipsum ipsum, tempor nec laoreet varius, ornare vitae est. In vitae dignissim massa.\
\
Nulla a dolor lacus. Quisque lacinia nunc mollis orci tincidunt non tempor lacus porttitor. Quisque et libero vitae mi commodo accumsan. Duis fringilla dapibus sem. Integer lobortis lectus vitae justo tincidunt ullamcorper pellentesque orci laoreet. Donec eu sollicitudin sapien. Curabitur arcu mauris, aliquet eu ornare id, mattis nec nisl. Aliquam erat volutpat. Maecenas condimentum dapibus arcu, quis tincidunt nulla lacinia vel. Duis nisl augue, euismod eget scelerisque eu, lobortis at nulla. Fusce urna orci, rhoncus ut dictum et, malesuada nec elit. Morbi a dui risus. Nulla imperdiet, risus vitae lacinia scelerisque, enim ante blandit sapien, id faucibus risus odio sit amet dui. In vestibulum vestibulum arcu in consequat. Nunc ac felis ac elit condimentum fringilla non nec quam. Praesent sed erat nunc. Aenean porta nulla vitae arcu ultrices cursus. Sed eget ligula eget lorem molestie suscipit. Phasellus fringilla, magna quis pharetra mattis, lacus libero tempus tellus, ac faucibus purus libero sed mauris.\
\
Vivamus ac libero odio, vitae adipiscing libero. Curabitur at vehicula dui. Aenean fringilla tincidunt enim, at eleifend diam semper in. Nam mauris elit, scelerisque ut ornare et, tempus a lectus. Cras nec ante sem. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Cras convallis enim eget dui convallis et egestas urna condimentum. Pellentesque ultricies fringilla tincidunt. Morbi metus. ";

testString = "foo";
testString = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean non erat non tellus congue elementum. Donec consequat, odio non dictum vestibulum, nibh nibh accumsan odio, nec faucibus nibh eros ut quam. Sed et augue ligula, at tempus enim. Mauris sed lectus et eros pellentesque semper quis nec turpis. Phasellus nibh elit, varius vel viverra convallis, interdum eget nisl. Nulla lobortis turpis nec velit pharetra semper. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vestibulum fringilla ornare nisl, vel blandit justo pretium sit amet. Sed gravida sem et leo faucibus a ultrices est malesuada. Maecenas mollis tempor lectus sed luctus. Nulla sed mi eget dui pretium viverra ac a sem. Morbi congue, neque in adipiscing gravida, nibh dui feugiat metus, nec pellentesque lectus purus vitae massa. Aenean ut rhoncus dolor. Nullam id enim est, quis accumsan nulla. Donec porta laoreet consectetur. Maecenas at mi sit amet lorem tincidunt consequat sed nec tortor. Nam luctus vestibulum lorem eu cursus. Pellentesque vestibulum, quam vel sagittis iaculis, augue ante accumsan quam, nec consectetur eros augue quis quam. Fusce semper lectus ac arcu luctus iaculis. Praesent lacinia tincidunt mollis."
testString = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean non erat non tellus congue elementum. Donec consequat, odio non dictum vestibulum, nibh nibh accumsan odio, nec faucibus nibh eros ut quam. Sed et augue ligula, at tempus enim. Mauris sed lectus et eros pellentesque semper quis nec turpis. Phasellus nibh elit, varius vel viverra convallis, interdum eget nisl. Nulla lobortis turpis nec velit pharetra semper. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vestibulum fringilla ornare nisl, vel blandit justo pretium sit amet. Sed gravida sem et leo faucibus a ultrices est malesuada. Maecenas mollis tempor lectus sed luctus. Nulla sed mi eget dui pretium viverra ac a sem. Morbi congue, neque in adipiscing gravida, nibh dui feugiat metus, nec pellentesque lectus purus vitae massa. Aenean ut rhoncus dolor. Nullam id enim est, quis accumsan nulla. Donec porta laoreet consectetur."
testString = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean non erat non tellus congue elementum. Donec consequat, odio non dictum vestibulum, nibh nibh accumsan odio, nec faucibus nibh eros ut quam. Sed et augue ligula, at tempus enim. Mauris sed lectus et eros pellentesque semper quis nec turpis. Phasellus nibh elit, varius vel viverra convallis, interdum eget nisl. Nulla lobortis turpis nec velit pharetra semper. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vestibulum fringilla ornare nisl, vel blandit justo pretium sit amet. Sed gravida sem et leo faucibus a ultrices est malesuada. Maecenas mollis tempor lectus sed luctus. Nulla sed mi eget dui pretium viverra ac a sem. Morbi congue, neque in adipiscing gravida, nibh dui feugiat metus, nec pellentesque lectus purus vitae massa. Aenean ut rhoncus dolor. Nullam id enim est, quis accumsan nulla. Donec porta laoreet consectetur. Maecenas at mi sit amet lorem tincidunt consequat sed nec tortor. Nam luctus vestibulum lorem eu cursus. Pellentesque vestibulum, quam vel sagittis iaculis, augue ante accumsan quam, nec consectetur eros augue quis quam. Fusce semper lectus ac arcu luctus iaculis. Praesent lacinia tincidunt mollis."

start = new Date().getMilliseconds();
result = testString.match(/^(.|\s){1,1000}$/);
finish = new Date().getMilliseconds();

if (result) {
	document.writeln("Matches");
} else {
	document.writeln("Doesn't match");
}
document.writeln(finish - start + " milliseconds");
